from .roles import Roles

PAGE_PERMISSIONS = {
    'AGCReconciliation': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'AnnualCompendium': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'AnnualReports': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'ATCViolationDaily': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'ATCViolationMonthly': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'ATCViolationWeekly': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'CongestionReport': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'DailyPSPReport': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'DayAheadForecastingError': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'Disbursements': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'DSMDisbursementLetter': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'DSMReconcilation': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'FinalSchedule': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'FRC': {'READ_PERMISSION': [Roles.ALL], 'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'GenerationOutage': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'GridEventsFlashreport': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'IntraDayForecastingError': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'LimitedTenders': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.CS_ADMIN]},
    'MeteringError': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'MeteringManual': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'MeteringSoftware': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'MonthAheadForecastingError': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'MonthlyDeviationReport': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'MonthlyReports': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'OpenTender': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.CS_ADMIN]},
    'PeakHours': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'PSDF': {'READ_PERMISSION': [Roles.ALL], 'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'QuarterlyReconciliationStatement': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'QuarterlyReports': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'RajbhasaPatrika': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.HR_ADMIN]},
    'ReactiveDisbursementLetter': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'ReactiveReconcilation': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'ReconciliationApplicant': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'ReconciliationCTU': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'RRASReconciliation': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.   MO_ADMIN]},
    'ScadavsSEM': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SCADA_ADMIN]},
    'SEMData': {'READ_PERMISSION': [Roles.ALL], 'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'ShutdownAvailedList': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'SingleTender': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.CS_ADMIN]},
    'SupplementaryAndPLIBill': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'TechnicalReports': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'Telemetry': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SCADA_ADMIN]},
    'TimeCorrectionManual': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]},
    'TransmissionElementAvailability': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'VDIDaily': {'READ_PERMISSION': [Roles.ALL], 'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'VDIMonthly': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'VDIWeekly': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'WeatherRelatedEvents': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'WeekAheadForecastingError': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'WeekAheadRollingForecast': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'WeeklyReports': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN,Roles.MO_ADMIN]},
    'YearAheadForecastingError': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.SO_ADMIN]},
    'Albums': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.HR_ADMIN]},
    'FTCDocuments': {'READ_PERMISSION': [Roles.ALL],'WRITE_PERMISSION': [Roles.MO_ADMIN]}
}